### ISSUE TITLE
Authentication not required

### ISSUE THREAD

**Issue by goalie1998** [babim/docker-squid#2]
When setting a user/password, the proxy will still connect if a user/password isn't supplied or if an incorrect one is supplied.

**Comment by Johnito** [comment]
Hey, i do not know if this is supposed to work that way, but this is what i do to have working authentification. Hope this helps : 

1. Add a **.htpasswd** file in your **/config** folder and paste your encrypted user/password in there ([see this](http://www.htaccesstools.com/htpasswd-generator/))
2. Edit **/config/squid.conf** to add the following code : 

```
auth_param basic program /usr/lib/squid3/basic_ncsa_auth /etc/squid3/.htpasswd
auth_param basic children 4
auth_param basic realm SET_YOUR_OWN_INVITE_TEXT
auth_param basic credentialsttl 2 hours
auth_param basic casesensitive off
acl authenticated proxy_auth REQUIRED
http_access allow authenticated
```

**Comment by goalie1998** [comment]
Worked like a charm. Thanks.

Jordan Smith

**Comment by babim** [comment]
I have simpleauth branch.
```
docker run -e USERNAME=foo -e PASSWORD=bar -p 3128:3128 --volume /srv/docker/squid/:/squid babim/squid:auth
```

**Comment by goalie1998** [comment]
I realized my mistake(s) in squid.conf. First I tested it within my network and allowed local traffic to connect. Then when I tested it outside my network, I left on allow all. 

Jordan Smith

**Comment by babim** [comment]
hihi. **ok**
