### ISSUE TITLE
squid_install.sh returned a non-zero code: 1

### ISSUE THREAD

**Issue by openarun** [babim/docker-squid#3]
Step 1/7 : FROM babim/alpinebase:3.9
---> 96e9bc7c252e
Step 2/7 : ENV SQUID_CACHE_DIR=/var/spool/squid SQUID_LOG_DIR=/var/log/squid SQUID_DIR=/squid SQUID_CONFIG_DIR=/etc/squid SQUID_USER=squid SOFT=squid
---> Running in 578a5ee0cbe5
Removing intermediate container 578a5ee0cbe5
---> 5e70683af80d
Step 3/7 : RUN apk add --no-cache wget bash && cd / && wget --no-check-certificate https://raw.githubusercontent.com/babim/docker-tag-options/master/z%20SCRIPT%20AUTO/option.sh && chmod 755 /option.sh
---> Running in df4fc4fdd733
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/1) Installing wget (1.20.3-r0)
Executing busybox-1.29.3-r10.trigger
OK: 22 MiB in 27 packages
[91m--2020-02-23 19:14:09-- https://raw.githubusercontent.com/babim/docker-tag-options/master/z%20SCRIPT%20AUTO/option.sh
[0m
[91mResolving raw.githubusercontent.com... [0m
[91m151.101.200.133
Connecting to raw.githubusercontent.com|151.101.200.133|:443... [0m
[91mconnected.
[0m
[91mHTTP request sent, awaiting response... [0m
[91m200 OK
Length: 21939 (21K) [text/plain]
Saving to: 'option.sh'
0K .........[0m
[91m. ..[0m
[91m........ . 100% 18.2M=0.001s
2020-02-23 19:14:09 (18.2 MB/s) - 'option.sh' saved [21939/21939]
[0m
Removing intermediate container df4fc4fdd733
---> affec0831f65
Step 4/7 : RUN wget --no-check-certificate -O - https://raw.githubusercontent.com/babim/docker-tag-options/master/z%20Squid%20install/${SOFT}_install.sh | bash
---> Running in 51520ae4d79b
[91m--2020-02-23 19:14:11-- https://raw.githubusercontent.com/babim/docker-tag-options/master/z%20Squid%20install/squid_install.sh
[0m
[91mResolving raw.githubusercontent.com... [0m
[91m151.101.248.133
Connecting to raw.githubusercontent.com|151.101.248.133|:443... [0m
[91mconnected.
[0m
[91mHTTP request sent, awaiting response... [0m
[91m200 OK
Length: 3288 (3.2K) [text/plain]
Saving to: 'STDOUT'
0K ... 100% 2.68M=0.001s
2020-02-23 19:14:11 (2.68 MB/s) - written to stdout [3288/3288]
[0m
Check and set download tool...
➜ Warning: Check and set download tool...
Calling: machine_has curl
use curl
Calling: machine_has curl
Calling: machine_has wget
Check root
You are logged in as root.
Check OS
Calling: get_osname
alpine linux
install squid apache2-utils..
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/13) Installing libuuid (2.33-r0)
(2/13) Installing apr (1.6.5-r0)
(3/13) Installing expat (2.2.8-r0)
(4/13) Installing apr-util (1.6.1-r5)
(5/13) Installing apache2-utils (2.4.41-r0)
(6/13) Installing popt (1.16-r7)
(7/13) Installing logrotate (3.15.0-r0)
(8/13) Installing libcap (2.26-r0)
(9/13) Installing db (5.3.28-r1)
(10/13) Installing libgcc (8.3.0-r0)
(11/13) Installing libltdl (2.4.6-r5)
(12/13) Installing libstdc++ (8.3.0-r0)
(13/13) Installing squid (4.8-r1)
Executing squid-4.8-r1.pre-install
Executing busybox-1.29.3-r10.trigger
OK: 33 MiB in 40 packages
Checking file: /docker-entrypoint.sh..
➜ Warning: /docker-entrypoint.sh not exists
Checking /docker-entrypoint.sh ..
/docker-entrypoint.sh does not exist
Downloading ...
Download file: docker-entrypoint.sh done
Checking file, folder: /docker-entrypoint.sh..
set mode to /docker-entrypoint.sh
Checking folder: /var/spool/squid..
Creating /var/spool/squid..
Checking folder: /var/spool/squid..
/var/spool/squid created
Checking folder: /var/log/squid..
➜ Warning: /var/log/squid exists
Checking folder: /squid..
Creating /squid..
Checking folder: /squid..
/squid created
Checking folder: /squid_start..
Creating /squid_start..
Checking folder: /squid_start..
/squid_start created
Checking file, folder: /var/spool/squid..
Checking file, folder: /squid/cache..
Removing intermediate container 51520ae4d79b
The command '/bin/sh -c wget --no-check-certificate -O - https://raw.githubusercontent.com/babim/docker-tag-options/master/z%20Squid%20install/${SOFT}_install.sh | bash' returned a non-zero code: 1

**Comment by babim** [comment]
thanks and fixed

**Comment by openarun** [comment]
Thanks for the fix ! :)
